### ISSUE TITLE
my advice

### ISSUE THREAD

**Issue by stlemon** [smlkts/HttpRequestClient#1]
Readme 太繁琐了，这不是个新手教程，所以没必要搞的这么啰嗦，简单整理下  purpose 和 how to use it就行了呗。代码贴的太多感觉体验不好，真正决定要用的人才会去仔细研究代码。但是大部分人在看Readme的时候还没确定呢。楼主加油吧！

**Comment by smlkts** [comment]
it's not a dropped-in framework and you must know how it works. It's not a final edition so the readme file will be updated sometimes. Please pay attention to the code.
